### PR TITLE
alzheimers

### PR DESCRIPTION
**Pull request by explosiveSlug2004**

### CODE REVIEW

**Comment by Zaprit** [comment]
what's the point of this? I forgot...

**Review by Slendy — APPROVED** [review]
whos zaprit and does anyone remember my name

**Review by sudokoko — APPROVED** [review]
lgtm
image

**Comment by explosiveSlug2004** [comment]
thank you for getting 5 professional developers to review me adding 5 lines of code that is one developer per line

**Comment by W0lf4llo** [comment]
lgtm

**Pull request merged**
